### ISSUE TITLE
Add option to sync github issues into Google Calendar

### ISSUE THREAD

**Issue by AngelicaRibeiro** [lucasvtiradentes/github-ticktick-gcal-sync#103]

**Comment by lucasvtiradentes** [comment]
oi @AngelicaRibeiro, obg por levantar esse ponto.

faz 2 meses que nao uso propriamente esse projeto. vou voltar agora em dezembro. 

voce tem algum feedback, algum erro estranho, etc?

**Comment by AngelicaRibeiro** [comment]
Olá @lucasvtiradentes, o plugin é muito bom! 

Até agora eu não notei nenhum bug em específico, ás vezes tem um delay para aparecer no calendário, mas nenhum delay muito longo. 

Como sugestão, eu colocaria a plavra 'commit' antes do nome do repositório no evento do Google Calendar. Isso ficaria mais fácil de identificar que evento é o quê.

E caso você esteja planejando implementar a incormporação das issues do Github no gCal, ficaria massa se você não só copiasse o link da issue em questão, mas desse um 'ctrl+c'  e  'ctrl+v' do seu conteúdo no corpo do evento do google calendar também. 

Isso no caso das issues que tiverem datas né! 
Então ficariam como um evento longo suponho. O que daria uma visão geral do que se tem para fazer e olhando pelo Gcal. O corpo do evento você pode deixar em markdown mesmo, por que esse conteúdo pode ser puxado direto do calendar para o obsidian usando um outro plugin ...

Abraço

**Comment by lucasvtiradentes** [comment]
Oi @AngelicaRibeiro, obg novamente pelos pontos.

e sim, irei fazer a parte dos issues, mas primeiro preciso fazer issues mais urgentes.

massa que voce usa o obsidian, eu amo esse app!

abraço!
