### ISSUE TITLE
[TypeError: Cannot read properties of undefined (reading 'tickTaskId')]

### ISSUE THREAD

**Issue by eliseboyd** [lucasvtiradentes/github-ticktick-gcal-sync#116]
I'm getting this error when trying to run the script - I've been using it without issues for the past few months, then a few weeks ago it stopped working.

<img width="546" alt="Screenshot 2024-09-16 at 22 36 34" src="https://github.com/user-attachments/assets/23b1707c-d072-4424-b621-b7e68c69c003">

**Comment by lucasvtiradentes** [comment]
I will work on this soon, can you provide your json configs? 

Make sure to not include tokens nor ticktick calendar links.
